DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS artist_profiles;
DROP TABLE IF EXISTS artworks;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS exhibitions;
DROP TABLE IF EXISTS exhibition_artworks;
DROP TABLE IF EXISTS invitations;

--- 1. USERS  (1.0.1)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

--- 2. ROLES (1.0.2)
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

--- 3. USER_ROLES (Join table, Many-To-Many connection) (1.0.3)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

--- 4. ARTIST_PROFILES (1.0.4)
CREATE TABLE artist_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    display_name VARCHAR(50) NOT NULL,
    bio TEXT NOT NULL,
    website VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

--- 5. ARTWORKS (1.1.1)
CREATE TABLE artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_profile_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    artwork_year INT NOT NULL,
    style VARCHAR(50) NOT NULL,
    image_path VARCHAR(255) NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (artist_profile_id) REFERENCES artist_profiles(id)
);

--- 6. REVIEWS (1.1.2)
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artwork_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (artwork_id) REFERENCES artworks(id),
    FOREIGN KEY (author_id) REFERENCES users(id)
);

--- 7. EXHIBITIONS (1.1.3)
CREATE TABLE exhibitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    curator_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (curator_id) REFERENCES users(id)
);


--- 8. EXHIBITION_ARTWORKS (Join table, Many-To-Many connection) (1.1.4)
CREATE TABLE exhibition_artworks (
    exhibition_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    PRIMARY KEY (exhibition_id, artwork_id),
    FOREIGN KEY (exhibition_id) REFERENCES exhibitions(id),
    FOREIGN KEY (artwork_id) REFERENCES artworks(id)
);

--- 9. INVITATIONS (1.1.5)
CREATE TABLE invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exhibition_id BIGINT NOT NULL,
    artist_profile_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    UNIQUE (exhibition_id, artist_profile_id),
    FOREIGN KEY (exhibition_id) REFERENCES exhibitions(id),
    FOREIGN KEY (artist_profile_id) REFERENCES artist_profiles(id)
);